### PR TITLE
Adding alias to distribution after cert assigned

### PR DESCRIPTION
**Pull request by KristanMcDonald**
This adds functionality to add the alias after the certificate is assigned.

### CODE REVIEW

**Comment by pfulop** [comment]
If I understand it correctly, the domain for the certificate is different than the domain for which amazon requests it?

Also, I am not sure if this will work, our module runs close to the end of the deploy pipeline which means the changes you make to the compiledCloudFormationTemplate won't be deployed.

**Comment by KristanMcDonald** [comment]
So to illustrate:

    cfdDomain:
      domainName: kristan.mydomain.com
      cloudFront: myDomainDist
      retries: 15
      minimumProtocolVersion: TLSv1.2_2018
      enabled: true

will create the certificate for www.mydomain.com and attach it to the myDomainDist cloudfront distribution.

However, you end up with this:

image

So even if you set up a DNS record for kristan.mydomain.com pointing to the distribution, you can't visit kristan.mydomain.com and have it serve the content, because there's no alias.

If try to specify an alias in your cf script :

    Aliases : 
      - kristan.mydomain.com

I have tested it on our deployments and it worked ok for me, but worth testing!

What this does is attach the alias once the cert is valid and attached.

So what you end up with is : 
image

It works, I've tested it on our deployments :)

**Comment by pfulop** [comment]
Sorry for the delay, I was making some test serverless deployment to see what's your problem.

First I must say I was mistaken and the plugin runs before cloudformation file is uploaded (it's been a while).

Second, I tried the current version of the plugin and it seems to work. The plugin created a certificate for the specified domain and then attached the certificate to the CloudFront which had alias specified. I am therefore not sure where the issue lays.

**Comment by KristanMcDonald** [comment]
Could you share your cloudformation and serverless scrips? I’m unable to create a distribution with cert attached and alias specified without my changes.

**Comment by pfulop** [comment]
This is the config I just replaced domain and hosted zone id with something generic for sharing purposes here. I just deploy this with` sls deploy `and that's it. The alias and cert are assigned without the route53 records as well, you just won't be able to visit it since there's no association.

```yml
service: serverlessfesimple

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-cloudfront-distribution-certificate

custom:
  cfdDomain:
    domainNames:
      - "any.valid.domain"
    cloudFront: WebsiteDistribution
    retries: 15
    minimumProtocolVersion: TLSv1.2_2018
    enabled: true

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "serverlessfesimplespabuckettest"
        AccessControl: "PublicRead"
        WebsiteConfiguration:
          IndexDocument: "index.html"
          ErrorDocument: "index.html"

    WebsiteDistribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            TargetOriginId: "StaticSiteBucketOrigin"
            ViewerProtocolPolicy: "redirect-to-https"
            MaxTTL: 31536000 # one year
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: "none"
          Enabled: true
          PriceClass: "PriceClass_100"
          HttpVersion: "http2"
          IPV6Enabled: true
          Aliases:
            - "any.valid.domain"
          Origins:
            - Id: "StaticSiteBucketOrigin"
              DomainName: !GetAtt StaticSite.DomainName
              S3OriginConfig: {}

    DnsRecord:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: !GetAtt WebsiteDistribution.DomainName
          HostedZoneId: UNIQUEZONEID
        HostedZoneName: "valid.domain."
        Name: "any.valid.domain"
        Type: "A"
    DnsRecord6:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: !GetAtt WebsiteDistribution.DomainName
          HostedZoneId: UNIQUEZONEID
        HostedZoneName: "valid.domain."
        Name: "any.valid.domain"
        Type: "AAAA"

```

**Comment by KristanMcDonald** [comment]
Ok, you can close and ignore this! I found my problem, it was a typo in my serverless script.. Sorry and thanks for helping me figure this out!

**Pull request closed without merging**
